#     ____                                 _
#    / ___|  ___  _ __    ___  _ __  __ _ | |
#   | |  _  / _ \| '_ \  / _ \| '__|/ _` || |
#   | |_| ||  __/| | | ||  __/| |  | (_| || |
#    \____| \___||_| |_| \___||_|   \__,_||_|
#

configurationreloaded: "&b&lTechnoBlocks &8» &7Config reloaded" #/technoblocks reload message
noargsselect: "&b&lTechnoBlocks &8» &7No args selected" #No args used message
nopermsmsg: "&b&lTechnoBlocks &8» &cYou don't have permission"
nocreative: "&b&lTechnoBlocks &8» &cYou don't must be in creative"

#    ____   _               _
#   | __ ) | |  ___    ___ | | __ ___
#   |  _ \ | | / _ \  / __|| |/ // __|
#   | |_) || || (_) || (__ |   < \__ \
#   |____/ |_| \___/  \___||_|\_\|___/
#

timerforblock: 60 #This is the value MEASURED IN TICK (20 ticks = 1 second) of the time that the block after its placement will take to eliminate itself

block1: #Default block (Block that is given back to you when you die or you left and rejoin in the server)
  blocktype: WOOL #Type of block
  slotonjoin: 4 #ONLY FOR DEFAULT BLOCK
block2:
  blocktype: WOOD #Type of block
block3:
  blocktype: OBSIDIAN #Type of block

#     ____  _   _  ___
#    / ___|| | | ||_ _|
#   | |  _ | | | | | |
#   | |_| || |_| | | |
#    \____| \___/ |___|
#

gui:
  noperms: "&b&lTechnoBlocks &8» &cYou don't have permission to use Block Selector"
  guititle: '&8Block Selector' #Title of the GUI
  item1: #First Item
    type: WOOL #Type of item
    name: '&bWool' #Name of item
    lore: '&7Select wool' #Lore of item
    slotgive: 4 #Slot in which the block is placed
    quantitygive: 64 #Quantity of given blocks
  item2: #Second item
    type: WOOD #Type of item
    name: "&bWood" #Name of item
    lore: "&7Select Wood" #Lore of item
    slotgive: 4 #Slot in which the block is placed
    quantitygive: 64 #Quantity of given blocks
    missingpermission: "&b&lYou can't select this block!" #technoblocks.gui.use.item2
  item3: #Third item
    type: OBSIDIAN #Type of item
    name: "&bObsidian" #Name of item
    lore: "&7Select obsidian" #Lore of item
    slotgive: 4 #Slot in which the block is placed
    quantitygive: 64 #Quantity of given blocks
    missingpermission: "&b&lYou can't select this block!" #technoblocks.gui.use.item3
